// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7NH2c3ShiTC9YrMhCIr1VaJ-LlX3n5D4',
    appId: '1:423526810613:android:0e5558b2c1025af67956bc',
    messagingSenderId: '423526810613',
    projectId: 'cloud-firestore-6a6e4',
    storageBucket: 'cloud-firestore-6a6e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWh9Al-Jc3ppoBaJvbBjGcXqNURmLW-C0',
    appId: '1:423526810613:ios:7f30214d639818697956bc',
    messagingSenderId: '423526810613',
    projectId: 'cloud-firestore-6a6e4',
    storageBucket: 'cloud-firestore-6a6e4.appspot.com',
    iosBundleId: 'com.example.flutterPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWh9Al-Jc3ppoBaJvbBjGcXqNURmLW-C0',
    appId: '1:423526810613:ios:7f30214d639818697956bc',
    messagingSenderId: '423526810613',
    projectId: 'cloud-firestore-6a6e4',
    storageBucket: 'cloud-firestore-6a6e4.appspot.com',
    iosBundleId: 'com.example.flutterPractice',
  );
}
